<?php

namespace CollDev\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JokeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JokeRepository extends EntityRepository
{
}
